Repository sbt/sbt-jni, pull requests merged in 2024-10, with the labels that each got.

#217 Update scala-compiler, scala-library, ... to 2.13.15
  build.sbt
  plugin/src/sbt-test/sbt-jni/overloads/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple-cargo/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple-meson/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple-syntax/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple/project/ScriptedHelper.scala
Labels: dependency-update

#218 Update asm to 9.7.1
  build.sbt
Labels: dependencies

#220 Update sbt-ci-release to 1.7.0
  project/plugins.sbt
Labels: dependencies

#222 add parentheses `PathFinder.get`
  plugin/src/main/scala/com/github/sbt/jni/build/Cargo.scala
  plugin/src/main/scala/com/github/sbt/jni/plugins/JniPackage.scala
Labels: enhancement

#221 Update sbt-ci-release to 1.8.0
  project/plugins.sbt
Labels: build

#223 Update sbt, scripted-plugin to 1.10.3
  plugin/src/sbt-test/sbt-jni/simple/project/build.properties
  project/build.properties
Labels: dependencies

#224 Update sbt-ci-release to 1.9.0
  project/plugins.sbt
Labels: build

#225 Update scala3-compiler, scala3-library to 3.5.2
  build.sbt
  plugin/src/sbt-test/sbt-jni/simple-syntax/project/ScriptedHelper.scala
Labels: dependencies
