Repository sbt/sbt-jni, pull requests merged in 2024-05, with the labels that each got.

#204 Drop JDK8 builds
  .github/workflows/ci.yml
  build.sbt
  plugin/src/sbt-test/sbt-jni/overloads/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/overloads/project/build.properties
  plugin/src/sbt-test/sbt-jni/simple-cargo/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple-cargo/project/build.properties
  plugin/src/sbt-test/sbt-jni/simple-meson/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple-meson/project/build.properties
  plugin/src/sbt-test/sbt-jni/simple-syntax/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple-syntax/project/build.properties
  plugin/src/sbt-test/sbt-jni/simple/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple/project/build.properties
  project/build.properties
Labels: build

#173 Fix Rust target-dir with spaces
  plugin/src/main/scala/com/github/sbt/jni/build/Cargo.scala
  plugin/src/main/scala/com/github/sbt/jni/build/package.scala
  plugin/src/sbt-test/sbt-jni/simple cargo with space/README.md
  plugin/src/sbt-test/sbt-jni/simple cargo with space/build.sbt
  plugin/src/sbt-test/sbt-jni/simple cargo with space/core
  plugin/src/sbt-test/sbt-jni/simple cargo with space/native
  plugin/src/sbt-test/sbt-jni/simple cargo with space/project
  plugin/src/sbt-test/sbt-jni/simple cargo with space/test
Labels: bug

#205 Update scala3-compiler, scala3-library to 3.4.2
  build.sbt
  plugin/src/sbt-test/sbt-jni/simple-syntax/project/ScriptedHelper.scala
Labels: dependencies
