Repository sbt/sbt-jni, pull requests merged in 2025-01, with the labels that each got.

#233 Fix DLL not found on Windows
  plugin/src/main/scala/com/github/sbt/jni/build/Cargo.scala
  plugin/src/main/scala/com/github/sbt/jni/build/ConfigureMakeInstall.scala
Labels: enhancement

#235 Update scala-compiler, scala-library, ... to 2.13.16
  build.sbt
  plugin/src/sbt-test/sbt-jni/overloads/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple-cargo/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple-meson/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple-syntax/project/ScriptedHelper.scala
  plugin/src/sbt-test/sbt-jni/simple/project/ScriptedHelper.scala
Labels: dependencies

#237 Update scalafmt-core to 3.8.5
  .scalafmt.conf
Labels: build

#239 Update scala3-compiler, scala3-library to 3.6.3
  build.sbt
  plugin/src/sbt-test/sbt-jni/simple-syntax/project/ScriptedHelper.scala
Labels: dependencies

#240 Update scalafmt-core to 3.8.6
  .scalafmt.conf
Labels: build
